language: php

php:
    - 5.5
    - 5.4
    - 5.3

before_install:
    - set -ex

before_script:
    - cd $TRAVIS_BUILD_DIR
    - composer install --dev --no-interaction --prefer-source
    - export PATH="$TRAVIS_BUILD_DIR/vendor/bin/:$PATH"
    - wp boilerplate version

script:
    - exit 0